Repository ProjectRunners/toonners, pull requests merged in 2024-06, with the labels that each got.

#162 [BE] 피드 기능 오류 수정
  BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/response/ChildFeedResponse.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/service/FeedService.java
Labels: backend, fix

#164 [BE] 배포 경로 수정
  scripts/gh_deploy.sh
Labels: backend, fix

#166 [BE] 채팅방 생성 오류 수정
  .github/workflows/deploy.yml
  BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/service/ChatRoomService.java
Labels: backend, fix

#168 [BE] 내가 참여 중인 채팅방 조회 기능 추가
  BE/toonners/src/main/java/com/example/toonners/domain/chat/controller/ChatController.java
  BE/toonners/src/main/java/com/example/toonners/domain/chat/repository/ChatRepository.java
  BE/toonners/src/main/java/com/example/toonners/domain/chat/service/ChatService.java
Labels: backend, feature

#170 [BE] 회원 기능 추가 구현
  BE/toonners/src/main/java/com/example/toonners/config/AppConfig.java
  BE/toonners/src/main/java/com/example/toonners/config/jwt/TokenProvider.java
  BE/toonners/src/main/java/com/example/toonners/config/security/SecurityConfig.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/controller/FeedController.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/entity/Feed.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/service/FeedService.java
  BE/toonners/src/main/java/com/example/toonners/domain/member/controller/MemberController.java
  BE/toonners/src/main/java/com/example/toonners/domain/member/service/KakaoUserService.java
  BE/toonners/src/main/java/com/example/toonners/domain/member/service/MemberService.java
Labels: backend, feature

#173 [BE] 맴버 정보 조회 시 오류 수정
  BE/toonners/src/main/java/com/example/toonners/domain/member/service/MemberService.java
Labels: backend, fix

#179 [BE] 피드 정보 수정 기능 추가
  BE/toonners/src/main/java/com/example/toonners/domain/feed/controller/FeedController.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/request/ChildFeedRequest.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/request/UpdateFeedRequest.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/response/ChildFeedResponse.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/response/FeedInfoResponse.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/entity/Feed.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/repository/FeedRepository.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/service/FeedService.java
Labels: backend, feature

#180 [통합] 2024.06.07
  BE/toonners/src/main/java/com/example/toonners/domain/feed/controller/FeedController.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/request/ChildFeedRequest.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/request/UpdateFeedRequest.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/response/ChildFeedResponse.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/response/FeedInfoResponse.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/entity/Feed.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/repository/FeedRepository.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/service/FeedService.java
Labels: frontend, backend, feature

#183 [BE] 피드 별점 누락 수정
  BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/response/ChildFeedResponse.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/service/FeedService.java
Labels: backend, fix

#185 [BE] 피드 response 해시태그 2가지로 분류
  BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/response/FeedInfoResponse.java
Labels: backend, refactor

#187 [BE] 특정 맴버가 참여하고 있는 채팅방 조회 기능 추가
  BE/toonners/src/main/java/com/example/toonners/domain/chat/controller/ChatController.java
  BE/toonners/src/main/java/com/example/toonners/domain/chat/service/ChatService.java
Labels: backend, feature

#188 [통합] 2024.06.08
  BE/toonners/src/main/java/com/example/toonners/domain/chat/controller/ChatController.java
  BE/toonners/src/main/java/com/example/toonners/domain/chat/service/ChatService.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/response/ChildFeedResponse.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/response/FeedInfoResponse.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/service/FeedService.java
Labels: frontend, backend, feature, fix, refactor

#194 [BE] 피드 전체 조회 시 피드 나의 좋아여 여부 삽입
  BE/toonners/src/main/java/com/example/toonners/domain/feed/service/FeedService.java
Labels: backend, refactor

#195 [BE] 실시간 채팅방 조회를 위해 오늘 작성된 채팅 카운트
  BE/toonners/src/main/java/com/example/toonners/domain/chat/service/ChatService.java
  BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/ChatRoomScheduler.java
  BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/controller/ChatRoomController.java
  BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/dto/response/ChatRoomInfoResponse.java
  BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/entity/ChatRoom.java
  BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/repository/ChatRoomRepository.java
  BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/service/ChatRoomService.java
  BE/toonners/src/main/java/com/example/toonners/domain/fire/FireScheduler.java
  BE/toonners/src/main/java/com/example/toonners/domain/fire/service/FireService.java
  BE/toonners/src/main/java/com/example/toonners/exception/chatRoom/ChatRoomDoseNotExistException.java
  BE/toonners/src/main/java/com/example/toonners/exception/handler/ChatRoomExceptionHandler.java
Labels: backend, feature

#191 [FE] 오늘 뜬 웹툰 채팅방 검색 api 연결함
  FE/package-lock.json
  FE/package.json
  FE/src/api/feed.ts
  FE/src/api/reactQuery/useFeedQuery.ts
  FE/src/api/reactQuery/useFetchAllChat.ts
  FE/src/api/reactQuery/useFetchChatMessages.ts
  FE/src/api/reactQuery/useFetchChatRoomInfo.ts
  FE/src/api/reactQuery/useFetchFeedLikes.ts
  FE/src/api/reactQuery/useFetchMyTalk.ts
  FE/src/api/reactQuery/useFetchTodayChat.ts
  FE/src/api/reactQuery/useFetchTopChatList.ts
  FE/src/assets/images/home/Fill.svg
  FE/src/assets/images/home/heart.svg
  FE/src/assets/images/login/heart.png
  FE/src/components/common/Like/index.tsx
  FE/src/components/home/chatroom/ChatRoomListFrame.tsx
  FE/src/components/home/chatroom/HomeChatRoomListFrame.tsx
  FE/src/components/home/chatroom/MyChatRoomItem.tsx
  FE/src/components/home/chatroom/RankingChatItem.tsx
  FE/src/components/home/chatroom/TodayChatItem.tsx
  FE/src/components/home/chatroom/main/ChatRoomMain.tsx
  FE/src/components/home/feed/FeedDetail.tsx
  FE/src/components/home/feed/FeedItem.tsx
  FE/src/main.tsx
  FE/src/pages/ChatroomPage.tsx
  FE/src/pages/FeedPage.tsx
  FE/src/pages/OtherPage/OtherPage.tsx
  FE/src/routes/HomeRoutes.tsx
  FE/src/styles/common/Like.module.scss
  FE/src/styles/home/Home.module.scss
Labels: frontend, design, feature

#197 [FE] 배포 테스트를 위한 pr
  BE/toonners/src/main/java/com/example/toonners/domain/chat/service/ChatService.java
  BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/ChatRoomScheduler.java
  BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/controller/ChatRoomController.java
  BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/dto/response/ChatRoomInfoResponse.java
  BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/entity/ChatRoom.java
  BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/repository/ChatRoomRepository.java
  BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/service/ChatRoomService.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/service/FeedService.java
  BE/toonners/src/main/java/com/example/toonners/domain/fire/FireScheduler.java
  BE/toonners/src/main/java/com/example/toonners/domain/fire/service/FireService.java
  BE/toonners/src/main/java/com/example/toonners/exception/chatRoom/ChatRoomDoseNotExistException.java
  BE/toonners/src/main/java/com/example/toonners/exception/handler/ChatRoomExceptionHandler.java
  FE/package-lock.json
  FE/package.json
  FE/src/api/feed.ts
  FE/src/api/reactQuery/useFeedQuery.ts
  FE/src/api/reactQuery/useFetchAllChat.ts
  FE/src/api/reactQuery/useFetchChatMessages.ts
  FE/src/api/reactQuery/useFetchChatRoomInfo.ts
  FE/src/api/reactQuery/useFetchFeedLikes.ts
  FE/src/api/reactQuery/useFetchMyTalk.ts
  FE/src/api/reactQuery/useFetchTodayChat.ts
  FE/src/api/reactQuery/useFetchTopChatList.ts
  FE/src/assets/images/home/Fill.svg
  FE/src/assets/images/home/heart.svg
  FE/src/assets/images/login/heart.png
  FE/src/components/common/Like/index.tsx
  FE/src/components/home/chatroom/ChatRoomListFrame.tsx
  FE/src/components/home/chatroom/HomeChatRoomListFrame.tsx
  FE/src/components/home/chatroom/MyChatRoomItem.tsx
  FE/src/components/home/chatroom/RankingChatItem.tsx
  FE/src/components/home/chatroom/TodayChatItem.tsx
  FE/src/components/home/chatroom/main/ChatRoomMain.tsx
  FE/src/components/home/feed/FeedDetail.tsx
  FE/src/components/home/feed/FeedItem.tsx
  FE/src/main.tsx
  FE/src/pages/ChatroomPage.tsx
  FE/src/pages/FeedPage.tsx
  FE/src/pages/OtherPage/OtherPage.tsx
  FE/src/routes/HomeRoutes.tsx
  FE/src/styles/common/Like.module.scss
  FE/src/styles/home/Home.module.scss
Labels: frontend, backend, design, feature, fix, refactor

#199 Feat/front issue198
  FE/src/App.tsx
  FE/src/api/feed.ts
  FE/src/api/myPage.ts
  FE/src/api/reactQuery/useFeedQuery.ts
  FE/src/api/recommend.ts
  FE/src/components/common/Like/index.tsx
  FE/src/components/home/chatroom/create/CreateChatRoom2.tsx
  FE/src/components/home/feed/FeedDetail.tsx
  FE/src/components/home/feed/FeedItem.tsx
  FE/src/pages/FeedPage.tsx
  FE/src/pages/ModifyRecommend.tsx
  FE/src/pages/Mypage.tsx
  FE/src/pages/NewRecommend/Step1.tsx
  FE/src/pages/NewRecommend/Step3.tsx
  FE/src/pages/Signup/Signup2.tsx
  FE/src/pages/Signup/Signup3.tsx
  FE/src/slices/useRecommendationStore.ts
  FE/src/styles/makeRecommend/makeRecommend.module.scss
Labels: frontend, design, feature, fix, refactor

#201 [FE] 피드 삭제기능 추가
  FE/src/api/feed.ts
  FE/src/components/common/Button/delete.tsx
  FE/src/components/common/Button/index.tsx
  FE/src/components/common/Modal/index.tsx
  FE/src/pages/NewRecommend/Step1.tsx
  FE/src/styles/common/Button.module.scss
  FE/src/styles/common/Modal.module.scss
Labels: frontend, design, feature

#204 [BE] 로그아웃 시 발생하는 오류 수정 1
  BE/toonners/src/main/java/com/example/toonners/domain/member/controller/MemberController.java
  BE/toonners/src/main/java/com/example/toonners/domain/member/service/KakaoUserService.java
Labels: backend, fix

#205 [BE] 로그아웃 시 발생하는 오류 수정 2
  BE/toonners/src/main/java/com/example/toonners/domain/member/controller/MemberController.java
  BE/toonners/src/main/java/com/example/toonners/domain/member/service/KakaoUserService.java
Labels: backend, fix

#208 [BE] 요일 기준으로 채팅방 조회
  BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/controller/ChatRoomController.java
  BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/service/ChatRoomService.java
Labels: backend, feature

#209 [BE] 오늘 요일이 정확이 들어가고 있는지 체크
  BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/service/ChatRoomService.java
Labels: backend, fix

#211 [BE] 오늘 업데이트 예정인 웹툰 채팅방 조회 기능 수정
  BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/repository/ChatRoomRepository.java
  BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/service/ChatRoomService.java
  BE/toonners/src/main/resources/application.yml
Labels: backend, fix

#212 [BE] 오늘 업데이트 예정인 웹툰 채팅방 조회 기능 수정2 - 동일한 시간대 설정
  BE/toonners/src/main/java/com/example/toonners/ToonnersApplication.java
Labels: backend, fix

#213 [BE] 로그인/회원가입 시 발생하는 오류 수정 1
  BE/toonners/src/main/java/com/example/toonners/domain/member/service/KakaoUserService.java
Labels: backend, fix

#214 [FE] try-catch 제거 및 에러 처리 위치 변경
  FE/src/api/feed.ts
  FE/src/api/myPage.ts
  FE/src/components/home/chatroom/HomeChatRoomListFrame.tsx
  FE/src/pages/ChatroomPage.tsx
  FE/src/pages/Login.tsx
  FE/src/pages/Mypage.tsx
  FE/src/pages/OtherPage/OtherPage.tsx
  FE/src/pages/mypage/EditLikedWtnPage.tsx
  FE/src/pages/mypage/EditSeeWtnPage.tsx
  FE/src/pages/mypage/MyFeedPage.tsx
  FE/src/pages/mypage/MyScrapPage.tsx
  FE/src/routes/Signup.tsx
Labels: frontend, feature, refactor

#216 [BE] 중복쿼리 수정 및 소셜 로그인 과정 일부 에러처리 상세화
  BE/toonners/src/main/java/com/example/toonners/domain/member/service/KakaoUserService.java
  BE/toonners/src/main/java/com/example/toonners/domain/member/service/MemberService.java
Labels: backend, refactor

#218 [FE] 채팅방 더보기 검색기능 추가 및 잘못된 경로 페이지 추가
  FE/src/App.tsx
  FE/src/api/myPage.ts
  FE/src/components/home/chatroom/ChatRoomListFrame.tsx
  FE/src/pages/Mypage.tsx
  FE/src/pages/WrongPath.tsx
  FE/src/styles/makeRecommend/makeRecommend.module.scss
  FE/src/styles/wrong/index.module.scss
Labels: frontend, design, docs, feature

#219 [FE] 가독성과 유지보수를 위한 코드 리펙토링
  FE/src/App.tsx
  FE/src/api/myPage.ts
  FE/src/components/Webtoon/ClickedWebtoonCard.tsx
  FE/src/components/Webtoon/SearchWebtoonBox.tsx
  FE/src/components/Webtoon/SearchedWebtoonCard.tsx
  FE/src/components/Webtoon/SelectedWebtoonBox.tsx
  FE/src/components/Webtoon/deleteBtn.tsx
  FE/src/components/Webtoon/plusBtn.tsx
  FE/src/components/common/Profile/index.tsx
  FE/src/components/home/chatroom/HomeChatRoomListFrame.tsx
  FE/src/components/mypage/ButtonNav.tsx
  FE/src/components/mypage/MainProfile.tsx
  FE/src/components/mypage/MyWebtoonContainer.tsx
  FE/src/components/mypage/Profile.tsx
  FE/src/components/newRecommend/Button.tsx
  FE/src/components/newRecommend/WebtoonCard.tsx
  FE/src/components/other/feedItem.tsx
  FE/src/components/search/SearchList.tsx
  FE/src/main.tsx
  FE/src/pages/ChatroomPage.tsx
  FE/src/pages/FeedPage.tsx
  FE/src/pages/HomePage.tsx
  FE/src/pages/Loding.tsx
  FE/src/pages/Login.tsx
  FE/src/pages/Mypage.tsx
  FE/src/pages/NewRecommend/Step1.tsx
  FE/src/pages/NewRecommend/Step2.tsx
  FE/src/pages/NewRecommend/Step3.tsx
  FE/src/pages/OtherPage/OtherPage.tsx
  FE/src/pages/Redirect.tsx
  FE/src/pages/SearchPage.tsx
  FE/src/pages/Signup/Signup3.tsx
  FE/src/pages/WrongPath.tsx
  FE/src/pages/mypage/EditMyWebtoonFrame.tsx
  FE/src/pages/mypage/EditSeeWtnPage.tsx
  FE/src/pages/mypage/FeedScrapPanel.tsx
  FE/src/pages/mypage/MyFeedPage.tsx
  FE/src/pages/mypage/MyScrapPage.tsx
  FE/src/routes/PrivateRoutes.tsx
  FE/src/styles/loading/index.module.scss
  FE/src/styles/mypage/Mypage.module.scss
  FE/src/styles/other/Other.module.scss
Labels: frontend, refactor

#221 [FE] 가독성과 유지보수를 고려한 코드 리펙토링
  FE/src/App.tsx
  FE/src/components/home/feed/FeedDetail.tsx
  FE/src/components/other/feedItem.tsx
  FE/src/constants/ComponentTypes.ts
  FE/src/constants/ErrorTypes.ts
  FE/src/constants/SuccessTypes.ts
  FE/src/constants/Tags.ts
  FE/src/constants/pages/ChatroomPage.ts
  FE/src/hooks/useDebounce.ts
  FE/src/hooks/useFetchMyList.ts
  FE/src/hooks/useSearchQuery.ts
  FE/src/pages/ChatroomPage.tsx
  FE/src/pages/Mypage.tsx
  FE/src/pages/NewRecommend/Step1.tsx
  FE/src/pages/NewRecommend/Step2.tsx
  FE/src/pages/NewRecommend/Step3.tsx
  FE/src/pages/OtherPage/OtherPage.tsx
  FE/src/pages/Redirect.tsx
  FE/src/pages/Signup/Signup1.tsx
  FE/src/pages/Signup/Signup2.tsx
  FE/src/pages/Signup/Signup3.tsx
  FE/src/pages/mypage/EditMyWebtoonFrame.tsx
  FE/src/pages/mypage/FeedScrapPanel.tsx
  FE/src/routes/Signup.tsx
Labels: frontend, refactor

#224 [FE] 피드 좋아요 오류 수정 및 홈 웹툰 개수 수정
  FE/src/components/home/feed/FeedItem.tsx
  FE/src/constants/ErrorTypes.ts
  FE/src/pages/ChatroomPage.tsx
  FE/src/pages/Mypage.tsx
  FE/src/pages/NewRecommend/Step1.tsx
  FE/src/pages/NewRecommend/Step3.tsx
  FE/src/pages/Signup/Signup1.tsx
  FE/src/pages/Signup/Signup2.tsx
  FE/src/pages/mypage/EditMyWebtoonFrame.tsx
  FE/src/utils/isValidValue.ts
Labels: frontend, fix, refactor

#225 [FE] 유저 채팅 및 프로필 욕설 필터링 기능 추가
  FE/src/components/home/chatroom/main/ChatRoomMain.tsx
  FE/src/constants/ErrorTypes.ts
  FE/src/constants/Profanities.ts
  FE/src/pages/Signup/Signup1.tsx
  FE/src/utils/filterValue.ts
  FE/src/utils/isValidValue.ts
Labels: frontend, feature

#227 [FE] 사용자 입력 제한 기능 추가
  FE/src/api/fetchWetboonInfo.ts
  FE/src/api/myPage.ts
  FE/src/api/recommend.ts
  FE/src/constants/ErrorTypes.ts
  FE/src/constants/Profanities.ts
  FE/src/hooks/useFetchMyList.ts
  FE/src/interface/Webtoon.interface.ts
  FE/src/pages/Mypage.tsx
  FE/src/pages/Signup/Signup1.tsx
  FE/src/utils/isValidValue.ts
Labels: frontend, feature, fix, refactor

#229 [FE] 불필요한 웹툰 필터링 및 디자인 수정
  FE/src/api/fetchWetboonInfo.ts
  FE/src/components/Webtoon/plusBtn.tsx
  FE/src/components/home/chatroom/create/CreateChatRoom2.tsx
  FE/src/pages/Mypage.tsx
  FE/src/pages/NewRecommend/Step1.tsx
  FE/src/pages/OtherPage/OtherPage.tsx
  FE/src/styles/common/Tag.module.scss
  FE/src/styles/home/Home.module.scss
  FE/src/styles/makeRecommend/makeRecommend.module.scss
  FE/src/styles/other/Other.module.scss
Labels: frontend, design, feature, fix

#231 [FE] 유지보수를 위한 코드 컴포넌트 리펙토링 및 폴더 구조 변경
  FE/src/api/reactQuery/useChat.ts
  FE/src/api/reactQuery/useFeed.ts
  FE/src/api/reactQuery/useFeedQuery.ts
  FE/src/api/reactQuery/useFetchAllChat.ts
  FE/src/api/reactQuery/useFetchChatMessages.ts
  FE/src/api/reactQuery/useFetchChatRoomInfo.ts
  FE/src/api/reactQuery/useFetchFeedLikes.ts
  FE/src/api/reactQuery/useFetchMyTalk.ts
  FE/src/api/reactQuery/useFetchTodayChat.ts
  FE/src/api/reactQuery/useFetchTopChatList.ts
  FE/src/components/common/Button/Create.tsx
  FE/src/components/common/Like/index.tsx
  FE/src/components/home/chatroom/RankingChatItem.tsx
  FE/src/components/home/chatroom/create/CreateButton.tsx
  FE/src/components/home/chatroom/create/MakeChatBtn.tsx
  FE/src/components/home/chatroom/create/MakeFeedBtn.tsx
  FE/src/components/home/chatroom/main/ChatRoomMain.tsx
  FE/src/components/home/feed/FeedDetail.tsx
  FE/src/components/home/feed/FeedItem.tsx
  FE/src/pages/ChatroomPage.tsx
  FE/src/pages/FeedPage.tsx
Labels: frontend, fix, refactor

#233 [FE] 로딩창 추가 및 바텀 내브 바 고정
  FE/src/hooks/useDebounce.ts
  FE/src/pages/ChatroomPage.tsx
  FE/src/pages/FeedPage.tsx
  FE/src/pages/Loding.tsx
  FE/src/styles/common/Button.module.scss
  FE/src/styles/home/Home.module.scss
  FE/src/styles/loading/index.module.scss
Labels: frontend, design

#235 [FE] 기존의 unknown API 리턴 타입 명시하기
  FE/src/api/chat.ts
  FE/src/api/feed.ts
  FE/src/api/myPage.ts
  FE/src/api/reactQuery/useChat.ts
  FE/src/api/reactQuery/useFeed.ts
  FE/src/api/recommend.ts
  FE/src/components/home/chatroom/ChatRoomListFrame.tsx
  FE/src/components/home/chatroom/HomeChatRoomListFrame.tsx
  FE/src/components/home/chatroom/MyChatRoom.tsx
  FE/src/interface/Mypage.interfate.ts
  FE/src/interface/Recommend.interface.ts
  FE/src/pages/ChatroomPage.tsx
  FE/src/slices/useRecommendationStore.ts
  FE/src/utils/isValidValue.ts
Labels: frontend, feature, fix, refactor

#237 [FE] feat: 분위기 장르 데이터 추가
  FE/src/constants/Tags.ts
  FE/src/styles/makeRecommend/makeRecommend.module.scss
Labels: design

#239 [FE] feat: 실시간 댓글 길어질때 처리
  FE/src/styles/home/Home.module.scss
Labels: frontend, design, feature

#241 [FE] design: 피드 카드 디자인 세부 수정
  FE/src/components/home/feed/FeedDetailCard.tsx
  FE/src/pages/FeedPage.tsx
  FE/src/pages/Loding.tsx
  FE/src/styles/home/Home.module.scss
Labels: design

#242 [BE] 피드 생성시 채팅방 별점 안되는 오류 수정
  BE/toonners/src/main/java/com/example/toonners/domain/feed/service/FeedService.java
Labels: backend, fix

#245 [BE] 회원탈퇴(멤버 삭제) 시 데이터 무결성 오류 수정
  BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/request/ChildFeedRequest.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/request/CreateFeedRequest.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/request/UpdateFeedRequest.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/response/ChildFeedResponse.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/entity/ChildFeedRequest.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/entity/Feed.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/service/FeedService.java
Labels: backend, fix

#247 [FE] 추천글 오류 수정 및 alert창 수정
  FE/src/api/myPage.ts
  FE/src/components/home/chatroom/ChatRoomListFrame.tsx
  FE/src/components/home/chatroom/MyChatRoom.tsx
  FE/src/components/home/chatroom/main/ChatRoomMain.tsx
  FE/src/pages/FeedPage.tsx
  FE/src/pages/Mypage.tsx
  FE/src/pages/NewRecommend/Step1.tsx
  FE/src/styles/home/Home.module.scss
Labels: frontend, design, fix, refactor

#250 [BE] 피드 db 구조 변경 후 조회 시 자식 피드 오류 수정
  BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/request/CreateFeedRequest.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/request/UpdateFeedRequest.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/response/ChildFeedResponse.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/entity/ChildFeed.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/entity/Feed.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/repository/ChildFeedRepository.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/service/FeedService.java
Labels: backend, fix

#251 [FE] 오류 수정
  FE/src/pages/FeedPage.tsx
  FE/src/pages/NewRecommend/Step1.tsx
  FE/src/pages/NewRecommend/Step2.tsx
  FE/src/pages/Signup/Signup2.tsx
  FE/src/pages/mypage/EditMyWebtoonFrame.tsx
Labels: frontend, fix

#253 [FE] fix: 웹툰 리스트 편집 오류 수정
  FE/src/interface/Mypage.interfate.ts
  FE/src/pages/mypage/EditMyWebtoonFrame.tsx
  FE/src/styles/signup/Signup.module.scss
  FE/src/styles/webtoon/SearchedWebtoonCard.module.scss
Labels: frontend, feature, fix

#255 [FE] style: tag 컴포넌트 span에 nowrap 추가
  FE/src/styles/common/Tag.module.scss
Labels: frontend, design

#257 [FE] fix: 유저 타입 오류 수정
  FE/src/api/fetchWetboonInfo.ts
  FE/src/components/home/chatroom/create/CreateChatRoom2.tsx
  FE/src/interface/Webtoon.interface.ts
  FE/src/pages/NewRecommend/Step2.tsx
  FE/src/pages/mypage/EditMyWebtoonFrame.tsx
Labels: frontend, fix

#259 [FE] fix: chat store type 오류 수정
  FE/src/slices/chatSlice.ts
Labels: frontend, fix
