Repository ProjectRunners/toonners, pull requests merged in 2024-05, with the labels that each got.

#20 [BE] feat: innit commit
  .idea/.gitignore
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/toonners.iml
  .idea/vcs.xml
  BE/toonners/.gitignore
  BE/toonners/build.gradle
  BE/toonners/gradle/wrapper/gradle-wrapper.jar
  BE/toonners/gradle/wrapper/gradle-wrapper.properties
  BE/toonners/gradlew
  BE/toonners/gradlew.bat
  BE/toonners/settings.gradle
  BE/toonners/src/main/java/com/example/toonners/ToonnersApplication.java
  BE/toonners/src/test/java/com/example/toonners/ToonnersApplicationTests.java
Labels: backend, setting

#22 [BE] 공통 사용할 클래스 생성
  BE/toonners/build.gradle
  BE/toonners/src/main/java/com/example/toonners/common/ApiResponse.java
  BE/toonners/src/main/java/com/example/toonners/common/BaseEntity.java
Labels: backend, feature

#26 [BE] 로컬 DB 연결
  BE/toonners/build.gradle
  BE/toonners/src/main/resources/application.properties
Labels: backend, setting

#24 [FE] Routing 설정
  FE/src/App.tsx
  FE/src/main.tsx
  FE/src/pages/Login.tsx
  FE/src/routes/NewChatRoom.tsx
  FE/src/routes/NewRecomand.tsx
  FE/src/routes/Signup.tsx
  FE/src/styles/login/LoginPage.module.scss
Labels: frontend, feature

#31 [FE] 메인 페이지 컴포넌트 생성
  FE/package.json
  FE/src/App.tsx
  FE/src/components/common/Logo/index.tsx
  FE/src/components/common/Profile/index.tsx
  FE/src/components/common/Tag/index.tsx
  FE/src/components/home/BottomNav.tsx
  FE/src/components/home/HomeTab.tsx
  FE/src/components/home/chatroom/ChatRoomList.tsx
  FE/src/components/home/chatroom/MyChatRoom.tsx
  FE/src/components/home/chatroom/MyChatRoomItem.tsx
  FE/src/components/home/chatroom/RankingChat.tsx
  FE/src/components/home/chatroom/RankingChatItem.tsx
  FE/src/components/home/chatroom/RestChat.tsx
  FE/src/components/home/chatroom/RestChatItem.tsx
  FE/src/components/home/chatroom/TodayChat.tsx
  FE/src/components/home/chatroom/TodayChatItem.tsx
  FE/src/components/home/feed/FeedItem.tsx
  FE/src/index.scss
  FE/src/main.tsx
  FE/src/pages/ChatroomPage.tsx
  FE/src/pages/CommonPage.tsx
  FE/src/pages/HomePage.tsx
  FE/src/pages/RecommendPage.tsx
  FE/src/routes/HomeRoutes.tsx
  FE/src/styles/common/Arrow.module.scss
  FE/src/styles/common/Logo.module.scss
  FE/src/styles/common/Profile.module.scss
  FE/src/styles/common/Tag.module.scss
  FE/src/styles/home/Home.module.scss
  FE/tsconfig.json
  FE/vite.config.ts
Labels: frontend, design, feature

#38 [BE] 회원 정보 수정 기능 추가
  BE/toonners/src/main/java/com/example/toonners/domain/member/controller/MemberController.java
  BE/toonners/src/main/java/com/example/toonners/domain/member/dto/request/UpdateMemberRequest.java
  BE/toonners/src/main/java/com/example/toonners/domain/member/entity/Member.java
  BE/toonners/src/main/java/com/example/toonners/domain/member/service/MemberService.java
  BE/toonners/src/main/java/com/example/toonners/exception/member/UnauthorizedRequestException.java
Labels: backend, feature

#37 [FE] 프로필 등록 페이지 생성 및 병합 충돌 해결(rebase)
  .DS_Store
  FE/src/App.tsx
  FE/src/assets/images/login/KakaoImg.png
  FE/src/assets/images/login/main.png
  FE/src/components/Webtoon/SearchedWebtoonCard.tsx
  FE/src/components/common/InputWithButton/index.tsx
  FE/src/components/login/Button.tsx
  FE/src/components/login/KakaoButton.tsx
  FE/src/pages/Login.tsx
  FE/src/pages/Redirect.tsx
  FE/src/pages/Signup/Signup1.tsx
  FE/src/pages/Signup/Signup2.tsx
  FE/src/pages/Signup/Signup3.tsx
  FE/src/routes/Signup.tsx
  FE/src/styles/common/InputWithButton.module.scss
  FE/src/styles/login/Button.module.scss
  FE/src/styles/login/LoginPage.module.scss
  FE/src/styles/signup/Signup.module.scss
  FE/src/styles/signup/Signup2.module.scss
  FE/src/styles/webtoon/SearchedWebtoonCard.module.scss
  FE/src/vite-env.d.ts
Labels: frontend, feature, fix

#49 [FE] 공통 컴포넌트 수정
  FE/package-lock.json
  FE/package.json
  FE/src/assets/characters/character_1.svg
  FE/src/assets/characters/character_2.svg
  FE/src/assets/characters/character_3.svg
  FE/src/assets/characters/character_4.svg
  FE/src/assets/characters/character_5.svg
  FE/src/assets/characters/character_6.svg
  FE/src/assets/characters/character_7.svg
  FE/src/assets/characters/character_8.svg
  FE/src/assets/images/login/Kakao.svg
  FE/src/assets/images/login/KakaoImg.png
  FE/src/assets/images/login/MainImg.svg
  FE/src/assets/images/login/main.png
  FE/src/components/common/Badge/index.tsx
  FE/src/components/common/Button/Confirm.tsx
  FE/src/components/common/Button/Kakao.tsx
  FE/src/components/common/Button/index.tsx
  FE/src/components/common/Header/index.tsx
  FE/src/components/common/Input/index.tsx
  FE/src/components/common/InputWithButton/index.tsx
  FE/src/components/common/Rating/index.tsx
  FE/src/components/common/Tag/Bookmark.tsx
  FE/src/components/common/Tag/index.tsx
  FE/src/components/common/TextArea/index.tsx
  FE/src/components/home/chatroom/RankingChatItem.tsx
  FE/src/components/home/chatroom/RestChatItem.tsx
  FE/src/components/home/chatroom/TodayChatItem.tsx
  FE/src/components/home/chatroom/create/CreateChatRoom1.tsx
  FE/src/components/home/chatroom/create/CreateChatRoom2.tsx
  FE/src/components/home/chatroom/main/ChatRoomMain.tsx
  FE/src/components/home/feed/FeedItem.tsx
  FE/src/components/login/Button.tsx
  FE/src/components/login/KakaoButton.tsx
  FE/src/global.d.ts
  FE/src/index.scss
  FE/src/pages/CommonPage.tsx
  FE/src/pages/Login.tsx
  FE/src/pages/Signup/Signup3.tsx
  FE/src/styles/common/Badge.module.scss
  FE/src/styles/common/Button.module.scss
  FE/src/styles/common/Input.module.scss
  FE/src/styles/common/InputWithButton.module.scss
  FE/src/styles/common/Tag.module.scss
  FE/src/styles/home/ChatRoom.module.scss
  FE/src/styles/home/Home.module.scss
  FE/src/styles/login/LoginPage.module.scss
  FE/src/styles/signup/Signup.module.scss
  FE/src/vite-env.d.ts
  FE/tsconfig.json
  FE/vite.config.ts
Labels: frontend, design

#52 [FE] 공통 컴포넌트 적용 에러 수정
  FE/src/global.d.ts
  FE/src/pages/NewRecommend/Step1.tsx
  FE/src/svg.d.ts
  FE/tsconfig.json
Labels: frontend, fix

#55 [FE] 검색 페이지 컴포넌트 생성 및 네비게이션 연결
  FE/src/App.tsx
  FE/src/components/home/BottomNav.tsx
  FE/src/components/search/SearchList.tsx
  FE/src/index.scss
  FE/src/pages/Login.tsx
  FE/src/pages/Redirect.tsx
  FE/src/pages/SearchPage.tsx
  FE/src/styles/Search.module.scss
Labels: frontend, design

#68 [BE] 회원 정보 수정 시 웝툰 데이터 db 삽입
  BE/toonners/src/main/java/com/example/toonners/domain/member/dto/request/SignUpRequest.java
  BE/toonners/src/main/java/com/example/toonners/domain/member/dto/request/UpdateMemberRequest.java
  BE/toonners/src/main/java/com/example/toonners/domain/member/dto/response/InfoResponse.java
  BE/toonners/src/main/java/com/example/toonners/domain/member/entity/Member.java
  BE/toonners/src/main/java/com/example/toonners/domain/member/service/MemberService.java
Labels: backend, feature

#65 [BE] 채팅방 별 채팅 전체 조회
  BE/toonners/src/main/java/com/example/toonners/domain/chat/controller/ChatController.java
  BE/toonners/src/main/java/com/example/toonners/domain/chat/repository/ChatRepository.java
  BE/toonners/src/main/java/com/example/toonners/domain/chat/service/ChatService.java
  BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/dto/response/ChatRoomInfoResponse.java
Labels: backend, feature

#71 [BE] fix: 소셜 로그인 시 비밀번호 임의 삽입
  BE/toonners/src/main/java/com/example/toonners/domain/member/entity/Member.java
  BE/toonners/src/main/java/com/example/toonners/domain/member/service/KakaoUserService.java
Labels: backend, fix

#73 [FE] 카카오 로그인 API 연결
  BE/toonners/src/main/resources/application.properties
  FE/src/App.tsx
  FE/src/pages/Login.tsx
  FE/src/pages/Redirect.tsx
Labels: frontend, feature

#75 [FE] 채팅방 생성 및 조회 API 연결
  FE/src/api/JsonAxios.ts
  FE/src/api/chat.ts
  FE/src/components/home/chatroom/ChatRoomListFrame.tsx
  FE/src/components/home/chatroom/HomeChatRoomListFrame.tsx
  FE/src/components/home/chatroom/RankingChat.tsx
  FE/src/components/home/chatroom/RestChat.tsx
  FE/src/components/home/chatroom/RestChatItem.tsx
  FE/src/components/home/chatroom/TodayChat.tsx
  FE/src/components/home/chatroom/TodayChatItem.tsx
  FE/src/components/home/chatroom/create/CreateChatRoom2.tsx
  FE/src/interface/ChatRoom.interface.ts
  FE/src/pages/ChatroomPage.tsx
  FE/src/pages/CommonPage.tsx
  FE/src/slices/chatSlice.ts
  FE/src/styles/home/Home.module.scss
  FE/src/vite-env.d.ts
  FE/tsconfig.json
  FE/vite.config.ts
Labels: frontend, design, feature

#77 [BE] 피드 생성 기능 추가
  BE/toonners/src/main/java/com/example/toonners/domain/feed/controller/FeedController.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/request/ChildFeedRequest.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/request/CreateFeedRequest.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/response/ChildFeedResponse.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/response/FeedInfoResponse.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/entity/Feed.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/repository/FeedRepository.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/service/FeedService.java
  BE/toonners/src/main/java/com/example/toonners/domain/member/service/MemberService.java
Labels: backend, feature

#81 [BE] 특정 맴버가 쓴 피드 조회 기능 추가
  BE/toonners/src/main/java/com/example/toonners/domain/feed/controller/FeedController.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/service/FeedService.java
Labels: backend, feature

#86 [BE] 북마크 기능 추가
  BE/toonners/src/main/java/com/example/toonners/domain/bookmark/controller/BookmarkController.java
  BE/toonners/src/main/java/com/example/toonners/domain/bookmark/entity/Bookmark.java
  BE/toonners/src/main/java/com/example/toonners/domain/bookmark/repository/BookmarkRepository.java
  BE/toonners/src/main/java/com/example/toonners/domain/bookmark/service/BookmarkService.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/response/FeedInfoResponse.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/service/FeedService.java
Labels: backend, feature

#87 [BE] 내가 북마크한 피드 리스트 조회 기능 추가
  BE/toonners/src/main/java/com/example/toonners/domain/bookmark/entity/Bookmark.java
  BE/toonners/src/main/java/com/example/toonners/domain/bookmark/repository/BookmarkRepository.java
  BE/toonners/src/main/java/com/example/toonners/domain/bookmark/service/BookmarkService.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/controller/FeedController.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/service/FeedService.java
Labels: backend, feature

#93 [BE] 웹툰 추천 시 마다 채팅방 별점 반영 기능
  BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/entity/ChatRoom.java
  BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/repository/ChatRoomRepository.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/service/FeedService.java
Labels: backend, feature

#96 [BE] 특정 회원 정보 조회 기능 추가
  BE/toonners/src/main/java/com/example/toonners/domain/member/controller/MemberController.java
  BE/toonners/src/main/java/com/example/toonners/domain/member/service/MemberService.java
Labels: backend, feature

#97 [FE] api 추가 및 수정 요청사항 반영
  FE/src/api/myPage.ts
  FE/src/api/recommend.ts
  FE/src/api/signup.ts
  FE/src/components/mypage/ButtonNav.tsx
  FE/src/interface/Mypage.interfate.ts
  FE/src/interface/Recommend.interface.ts
  FE/src/pages/Mypage.tsx
  FE/src/pages/NewRecommend/Step1.tsx
  FE/src/pages/NewRecommend/Step2.tsx
  FE/src/pages/NewRecommend/Step3.tsx
  FE/src/pages/mypage/EditLikedWtnPage.tsx
  FE/src/pages/mypage/EditSeeWtnPage.tsx
  FE/src/slices/useRecommendationStore.ts
  FE/src/styles/mypage/Mypage.module.scss
  FE/src/styles/signup/Signup.module.scss
  FE/src/styles/webtoon/SelectedWebtoonBox.module.scss
  FE/src/utils/authUtils.ts
Labels: frontend, design

#102 [BE] 누락된 피드 반환 값 추가
  BE/toonners/src/main/java/com/example/toonners/domain/feed/dto/response/FeedInfoResponse.java
Labels: backend, fix

#104 [BE] 채팅방 존재 여부 판별 기능
  BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/controller/ChatRoomController.java
  BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/service/ChatRoomService.java
Labels: backend, feature

#106 [BE] 채팅방 이름 일부로 채팅방 리스트 조회 기능
  BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/controller/ChatRoomController.java
  BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/repository/ChatRoomRepository.java
  BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/service/ChatRoomService.java
Labels: backend, feature

#107 [BE] 피드(게시글) 제목 일부로 피드 리스트 조회 기능
  BE/toonners/src/main/java/com/example/toonners/domain/feed/controller/FeedController.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/repository/FeedRepository.java
  BE/toonners/src/main/java/com/example/toonners/domain/feed/service/FeedService.java
Labels: backend, feature

#109 [FE] 채팅방 정보 조회 API 연결
  FE/src/api/chat.ts
  FE/src/components/common/InputWithButton/index.tsx
  FE/src/components/home/chatroom/main/Accordian.tsx
  FE/src/components/home/chatroom/main/ChatItem.tsx
  FE/src/components/home/chatroom/main/ChatRoomMain.tsx
  FE/src/components/home/feed/FeedItem.tsx
  FE/src/pages/CommonPage.tsx
  FE/src/pages/SearchPage.tsx
  FE/src/pages/Signup/Signup1.tsx
  FE/src/styles/common/InputWithButton.module.scss
  FE/src/styles/home/ChatRoom.module.scss
Labels: frontend, feature

#99 [FE] 메인페이지 피드 조회 API 연결
  FE/src/api/feed.ts
  FE/src/assets/images/home/Logo.svg
  FE/src/assets/images/login/Complete.svg
  FE/src/assets/images/login/MainImg.svg
  FE/src/components/common/Logo/index.tsx
  FE/src/components/common/Profile/index.tsx
  FE/src/components/common/Tag/Bookmark.tsx
  FE/src/components/home/feed/FeedItem.tsx
  FE/src/components/search/SearchList.tsx
  FE/src/interface/Feed.interface.ts
  FE/src/pages/FeedPage.tsx
  FE/src/pages/RecommendPage.tsx
  FE/src/pages/Signup/Signup3.tsx
  FE/src/routes/HomeRoutes.tsx
  FE/src/styles/common/Logo.module.scss
  FE/src/styles/common/Tag.module.scss
  FE/src/styles/home/Home.module.scss
  FE/src/styles/login/LoginPage.module.scss
  FE/src/styles/signup/Signup.module.scss
Labels: frontend, feature

#114 [BE] 회원 정보 조회 시 웹툰 관련 정보 누락 오류 수정
  BE/toonners/src/main/java/com/example/toonners/domain/member/service/MemberService.java
Labels: backend, fix

#115 [FE] 피드 상세페이지 컴포넌트 생성 및 조회 API 연결
  FE/src/App.tsx
  FE/src/api/feed.ts
  FE/src/components/common/Header/index.tsx
  FE/src/components/common/Tag/Bookmark.tsx
  FE/src/components/home/feed/FeedDetail.tsx
  FE/src/components/home/feed/FeedDetailCard.tsx
  FE/src/components/home/feed/FeedItem.tsx
  FE/src/interface/Feed.interface.ts
  FE/src/pages/NewRecommend/Step1.tsx
  FE/src/pages/NewRecommend/Step2.tsx
  FE/src/pages/NewRecommend/Step3.tsx
  FE/src/styles/common/Header.module.scss
  FE/src/styles/home/Home.module.scss
Labels: frontend, design, feature

#118 [FE] 메인페이지 추천글 조회 API 연결
  FE/src/api/myPage.ts
  FE/src/components/mypage/MainProfile.tsx
  FE/src/interface/Webtoon.interface.ts
  FE/src/pages/Mypage.tsx
  FE/src/pages/Redirect.tsx
  FE/src/pages/Signup/Signup3.tsx
  FE/src/pages/mypage/MyScrapPage.tsx
Labels: frontend, design, feature

#119 [FE] 검색 조회 API 연결
  FE/src/api/chat.ts
  FE/src/api/feed.ts
  FE/src/components/home/BottomNav.tsx
  FE/src/components/home/chatroom/main/ChatRoomMain.tsx
  FE/src/components/home/feed/FeedDetail.tsx
  FE/src/components/search/SearchList.tsx
  FE/src/interface/Feed.interface.ts
  FE/src/pages/HomePage.tsx
  FE/src/pages/SearchPage.tsx
  FE/src/styles/Search.module.scss
  FE/src/styles/home/Home.module.scss
Labels: frontend, feature

#123 [BE] modify: 채팅방 존재 판별 기능 반환 값 Long으로 변경
  BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/controller/ChatRoomController.java
  BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/service/ChatRoomService.java
Labels: backend, feature

#124 [BE] 인기 채팅방 조회 반환 값에 채팅 내역 포함
  BE/toonners/src/main/java/com/example/toonners/domain/chat/repository/ChatRepository.java
  BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/controller/ChatRoomController.java
  BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/dto/response/ChatRoomInfoResponse.java
  BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/repository/ChatRoomRepository.java
  BE/toonners/src/main/java/com/example/toonners/domain/chatRoom/service/ChatRoomService.java
Labels: backend, feature

#125 [FE] 실시간 인기 채팅방 조회 API 연결
  FE/src/api/chat.ts
  FE/src/components/common/Modal/index.tsx
  FE/src/components/home/chatroom/HomeChatRoomListFrame.tsx
  FE/src/components/home/chatroom/RankingChatItem.tsx
  FE/src/components/home/chatroom/create/CreateChatRoom1.tsx
  FE/src/components/home/chatroom/create/CreateChatRoom2.tsx
  FE/src/components/home/chatroom/main/ChatRoomMain.tsx
  FE/src/interface/ChatRoom.interface.ts
  FE/src/pages/ChatroomPage.tsx
  FE/src/styles/home/Home.module.scss
Labels: frontend, feature

#129 [BE] 서버 배포 push branch 변경
  .github/workflows/deploy.yml
Labels: backend

#130 [BE] 서버 배포 테스트 gradlew 위치 경로 재 설정
  .github/workflows/deploy.yml
Labels: backend

#131 [BE] fix: 서버 배포 테스트 Gradle build 있는 경로 재설정
  BE/toonners/appspec.yml
Labels: backend

#132 [BE] 서버 배포 테스트 working-directory 수정
  .github/workflows/deploy.yml
Labels: backend, fix

#133 [BE] 서버 배포 테스트 테스트 진행하지 않고 진행으로 수정
  BE/toonners/build.gradle
Labels: backend, fix

#134 [BE] 서버 배포 테스트 code deploy appilcation name 오타 수정
  .github/workflows/deploy.yml
Labels: backend, fix

#135 [FE] Private Router 설정
  FE/index.html
  FE/src/App.tsx
  FE/src/api/JsonAxios.ts
  FE/src/components/common/Badge/index.tsx
  FE/src/components/home/chatroom/RankingChatItem.tsx
  FE/src/components/home/chatroom/RestChatItem.tsx
  FE/src/components/home/chatroom/main/ChatRoomMain.tsx
  FE/src/components/home/feed/FeedItem.tsx
  FE/src/pages/ChatroomPage.tsx
  FE/src/pages/Login.tsx
  FE/src/pages/Redirect.tsx
  FE/src/routes/PrivateRoutes.tsx
  FE/src/styles/common/Header.module.scss
  FE/src/styles/home/Home.module.scss
Labels: frontend, feature

#144 [BE] MySQL 커넥터 종속성이 포함
  BE/toonners/build.gradle
Labels: backend, fix

#145 [FE] Redirect 에러 수정
  FE/src/api/JsonAxios.ts
Labels: frontend, feature

#148 [FE] 커서 모양 변경 및 오류 수정
  FE/index.html
  FE/public/favicon.svg
  FE/src/App.tsx
  FE/src/components/common/Badge/index.tsx
  FE/src/components/common/Header/index.tsx
  FE/src/components/common/Logo/index.tsx
  FE/src/components/home/chatroom/ChatRoomListFrame.tsx
  FE/src/components/home/chatroom/create/CreateChatRoom1.tsx
  FE/src/components/home/chatroom/create/CreateChatRoom2.tsx
  FE/src/components/home/chatroom/main/ChatRoomMain.tsx
  FE/src/components/home/feed/FeedDetail.tsx
  FE/src/components/home/feed/FeedDetailCard.tsx
  FE/src/components/home/feed/FeedItem.tsx
  FE/src/interface/Feed.interface.ts
  FE/src/pages/CommonPage.tsx
  FE/src/pages/NewRecommend/Step1.tsx
  FE/src/pages/NewRecommend/Step2.tsx
  FE/src/pages/NewRecommend/Step3.tsx
  FE/src/pages/SearchPage.tsx
  FE/src/pages/mypage/EditLikedWtnPage.tsx
  FE/src/pages/mypage/EditSeeWtnPage.tsx
  FE/src/pages/mypage/MyFeedPage.tsx
  FE/src/pages/mypage/MyScrapPage.tsx
  FE/src/styles/common/Header.module.scss
  FE/src/styles/common/Logo.module.scss
  FE/src/styles/common/Profile.module.scss
  FE/src/styles/home/ChatRoom.module.scss
Labels: frontend, feature

#150 [FE] fix: 버그 삭제
  FE/src/api/fetchWetboonInfo.ts
  FE/src/pages/Mypage.tsx
  FE/src/pages/NewRecommend/Step3.tsx
  FE/src/pages/Signup/Signup2.1.tsx
  FE/src/pages/Signup/Signup2.tsx
  FE/src/pages/mypage/EditLikedWtnPage.tsx
Labels: frontend, design, feature, fix

#157 [BE] yml파일의 리다이렉트 주소 환경변수로 대신 표현
  BE/toonners/src/main/resources/application.yml
Labels: backend, refactor
